-- CASE1-15000 production controls
-- Run AFTER supabase/schema.sql.
-- This file is safe to rerun. It adds settlement locking, finalized-only investor views,
-- payout state synchronization, and audit logging.

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_audit_logs_created_at on public.audit_logs(created_at desc);
create index if not exists idx_audit_logs_entity on public.audit_logs(entity_type, entity_id);

alter table public.audit_logs enable row level security;
drop policy if exists "admin audit read" on public.audit_logs;
create policy "admin audit read" on public.audit_logs
for select to authenticated using (public.is_admin());
grant select on public.audit_logs to authenticated;

create or replace function public.write_audit(
  p_action text,
  p_entity_type text,
  p_entity_id uuid default null,
  p_details jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.audit_logs(actor_user_id, action, entity_type, entity_id, details)
  values ((select auth.uid()), p_action, p_entity_type, p_entity_id, coalesce(p_details, '{}'::jsonb));
end;
$$;

revoke all on function public.write_audit(text,text,uuid,jsonb) from public;
revoke all on function public.write_audit(text,text,uuid,jsonb) from authenticated;

-- Security-definer helpers avoid circular RLS dependencies.
create or replace function public.can_view_finalized_batch(p_batch_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_admin() or exists (
    select 1
    from public.settlement_batches b
    join public.weekly_settlements w on w.batch_id=b.id
    join public.investors i on i.id=w.investor_id
    where b.id=p_batch_id
      and b.status in ('confirmed','paid')
      and i.user_id=(select auth.uid())
  );
$$;

grant execute on function public.can_view_finalized_batch(uuid) to authenticated;

create or replace function public.can_view_finalized_settlement(p_investor_id uuid, p_batch_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_admin() or exists (
    select 1
    from public.investors i
    join public.settlement_batches b on b.id=p_batch_id
    where i.id=p_investor_id
      and i.user_id=(select auth.uid())
      and b.status in ('confirmed','paid')
  );
$$;

grant execute on function public.can_view_finalized_settlement(uuid,uuid) to authenticated;

-- Lock project-level settlement amounts after confirmation.
create or replace function public.guard_project_settlement_lock()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_batch_id uuid;
  v_status text;
begin
  if tg_op='DELETE' then v_batch_id:=old.batch_id; else v_batch_id:=new.batch_id; end if;
  select status into v_status from public.settlement_batches where id=v_batch_id;
  if v_status is distinct from 'draft' then
    raise exception '此週結算已鎖定，不能修改案件收益。';
  end if;
  if tg_op='DELETE' then return old; else return new; end if;
end;
$$;

drop trigger if exists guard_project_settlement_lock on public.project_settlements;
create trigger guard_project_settlement_lock
before insert or update or delete on public.project_settlements
for each row execute function public.guard_project_settlement_lock();

-- Locked weekly rows may only change payout fields / note, not the financial allocation.
create or replace function public.guard_weekly_settlement_lock()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_batch_id uuid;
  v_status text;
begin
  if tg_op='DELETE' then v_batch_id:=old.batch_id; else v_batch_id:=new.batch_id; end if;
  select status into v_status from public.settlement_batches where id=v_batch_id;

  if tg_op in ('INSERT','DELETE') and v_status is distinct from 'draft' then
    raise exception '此週結算已鎖定，不能新增或刪除收益分配。';
  end if;

  if tg_op='UPDATE' and v_status is distinct from 'draft' then
    if new.batch_id is distinct from old.batch_id
       or new.project_settlement_id is distinct from old.project_settlement_id
       or new.project_id is distinct from old.project_id
       or new.investor_id is distinct from old.investor_id
       or new.participation_id is distinct from old.participation_id
       or new.invested_amount is distinct from old.invested_amount
       or new.profit_amount is distinct from old.profit_amount then
      raise exception '此週結算已鎖定，只能更新撥款狀態或備註。';
    end if;
  end if;

  if tg_op='DELETE' then return old; else return new; end if;
end;
$$;

drop trigger if exists guard_weekly_settlement_lock on public.weekly_settlements;
create trigger guard_weekly_settlement_lock
before insert or update or delete on public.weekly_settlements
for each row execute function public.guard_weekly_settlement_lock();

-- Only allow forward confirmation / payout transitions. paid -> confirmed is allowed when a payout is reverted.
create or replace function public.guard_batch_transition()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if tg_op='DELETE' then
    if old.status <> 'draft' then raise exception '已確認的結算批次不可刪除。'; end if;
    return old;
  end if;

  if new.status is distinct from old.status and not (
    (old.status='draft' and new.status='confirmed') or
    (old.status='confirmed' and new.status='paid') or
    (old.status='paid' and new.status='confirmed')
  ) then
    raise exception '不允許的結算狀態轉換：% -> %', old.status, new.status;
  end if;
  return new;
end;
$$;

drop trigger if exists guard_batch_transition on public.settlement_batches;
create trigger guard_batch_transition
before update or delete on public.settlement_batches
for each row execute function public.guard_batch_transition();

create or replace function public.allocate_project_week_safe(
  p_week_start date,
  p_week_end date,
  p_project_id uuid,
  p_gross_profit numeric,
  p_fee_amount numeric default 0
)
returns setof public.weekly_settlements
language plpgsql
security definer
set search_path = public
as $$
declare
  v_batch uuid;
  v_status text;
  v_ps uuid;
  v_total numeric;
  v_net numeric;
begin
  if not public.is_admin() then raise exception 'admin only'; end if;
  if p_week_end < p_week_start then raise exception '週結束日不可早於週起始日。'; end if;
  v_net := p_gross_profit - coalesce(p_fee_amount,0);
  if v_net < 0 then raise exception '費用不可高於本週總收益。'; end if;

  select id,status into v_batch,v_status
  from public.settlement_batches
  where week_start=p_week_start and week_end=p_week_end
  for update;

  if v_batch is null then
    insert into public.settlement_batches(week_start,week_end,status,created_by)
    values(p_week_start,p_week_end,'draft',(select auth.uid()))
    returning id,status into v_batch,v_status;
  elsif v_status <> 'draft' then
    raise exception '此週結算已確認鎖定，無法重新計算。';
  end if;

  insert into public.project_settlements(batch_id,project_id,gross_profit,fee_amount)
  values(v_batch,p_project_id,p_gross_profit,coalesce(p_fee_amount,0))
  on conflict(batch_id,project_id) do update
    set gross_profit=excluded.gross_profit,
        fee_amount=excluded.fee_amount
  returning id into v_ps;

  select coalesce(sum(amount),0) into v_total
  from public.participations
  where project_id=p_project_id
    and status='active'
    and start_date<=p_week_end
    and (end_date is null or end_date>=p_week_start);

  if v_total<=0 then raise exception '此投資案沒有有效參與金額。'; end if;

  delete from public.weekly_settlements
  where batch_id=v_batch and project_id=p_project_id;

  insert into public.weekly_settlements(
    batch_id,project_settlement_id,project_id,investor_id,participation_id,
    invested_amount,profit_amount,payout_status
  )
  select v_batch,v_ps,p_project_id,p.investor_id,p.id,p.amount,
         round(v_net*p.amount/v_total,4),'pending'
  from public.participations p
  where p.project_id=p_project_id
    and p.status='active'
    and p.start_date<=p_week_end
    and (p.end_date is null or p.end_date>=p_week_start);

  perform public.write_audit(
    'allocate_week','project',p_project_id,
    jsonb_build_object(
      'batch_id',v_batch,
      'week_start',p_week_start,
      'week_end',p_week_end,
      'gross_profit',p_gross_profit,
      'fee_amount',coalesce(p_fee_amount,0)
    )
  );

  return query
  select * from public.weekly_settlements
  where batch_id=v_batch and project_id=p_project_id
  order by created_at;
end;
$$;

grant execute on function public.allocate_project_week_safe(date,date,uuid,numeric,numeric) to authenticated;

create or replace function public.confirm_settlement_batch(p_batch_id uuid)
returns public.settlement_batches
language plpgsql
security definer
set search_path = public
as $$
declare
  v_batch public.settlement_batches;
  v_count int;
begin
  if not public.is_admin() then raise exception 'admin only'; end if;

  select * into v_batch
  from public.settlement_batches
  where id=p_batch_id
  for update;

  if v_batch.id is null then raise exception '找不到結算批次。'; end if;
  if v_batch.status <> 'draft' then return v_batch; end if;

  select count(*) into v_count
  from public.weekly_settlements
  where batch_id=p_batch_id;
  if v_count=0 then raise exception '此批次尚無收益分配，不能確認。'; end if;

  update public.settlement_batches
  set status='confirmed'
  where id=p_batch_id
  returning * into v_batch;

  perform public.write_audit('confirm_batch','settlement_batch',p_batch_id,jsonb_build_object('rows',v_count));
  return v_batch;
end;
$$;

grant execute on function public.confirm_settlement_batch(uuid) to authenticated;

-- Keep batch status synchronized even when an admin changes payout_status directly.
create or replace function public.sync_batch_paid_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pending int;
  v_status text;
begin
  select status into v_status from public.settlement_batches where id=new.batch_id;
  if v_status not in ('confirmed','paid') then return new; end if;

  select count(*) into v_pending
  from public.weekly_settlements
  where batch_id=new.batch_id and payout_status<>'paid';

  if v_pending=0 and v_status='confirmed' then
    update public.settlement_batches set status='paid' where id=new.batch_id;
  elsif v_pending>0 and v_status='paid' then
    update public.settlement_batches set status='confirmed' where id=new.batch_id;
  end if;
  return new;
end;
$$;

drop trigger if exists sync_batch_paid_status on public.weekly_settlements;
create trigger sync_batch_paid_status
after update of payout_status on public.weekly_settlements
for each row execute function public.sync_batch_paid_status();

create or replace function public.set_settlement_paid(p_settlement_id uuid, p_paid boolean default true)
returns public.weekly_settlements
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.weekly_settlements;
  v_batch_status text;
begin
  if not public.is_admin() then raise exception 'admin only'; end if;

  select * into v_row
  from public.weekly_settlements
  where id=p_settlement_id
  for update;

  if v_row.id is null then raise exception '找不到收益紀錄。'; end if;

  select status into v_batch_status
  from public.settlement_batches
  where id=v_row.batch_id
  for update;

  if v_batch_status='draft' then raise exception '請先確認並鎖定本週結算，再進行撥款。'; end if;

  update public.weekly_settlements
  set payout_status=case when p_paid then 'paid' else 'pending' end,
      paid_at=case when p_paid then now() else null end
  where id=p_settlement_id
  returning * into v_row;

  perform public.write_audit(
    case when p_paid then 'mark_paid' else 'revert_paid' end,
    'weekly_settlement',p_settlement_id,
    jsonb_build_object('batch_id',v_row.batch_id,'profit_amount',v_row.profit_amount)
  );

  return v_row;
end;
$$;

grant execute on function public.set_settlement_paid(uuid,boolean) to authenticated;

-- Finalized-only investor visibility.
drop policy if exists "authenticated batches read" on public.settlement_batches;
drop policy if exists "authorized batches read" on public.settlement_batches;
create policy "authorized finalized batches read" on public.settlement_batches
for select to authenticated using (public.can_view_finalized_batch(id));

drop policy if exists "own weekly settlements read" on public.weekly_settlements;
drop policy if exists "own finalized weekly settlements read" on public.weekly_settlements;
create policy "own finalized weekly settlements read" on public.weekly_settlements
for select to authenticated using (public.can_view_finalized_settlement(investor_id,batch_id));

-- Audit direct admin changes to master data and settlement rows.
create or replace function public.audit_row_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
  v_details jsonb;
begin
  if tg_op='DELETE' then v_id:=old.id; else v_id:=new.id; end if;
  v_details := jsonb_build_object(
    'operation',tg_op,
    'before',case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) else null end,
    'after',case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) else null end
  );
  perform public.write_audit(lower(tg_op),tg_table_name,v_id,v_details);
  if tg_op='DELETE' then return old; else return new; end if;
end;
$$;

drop trigger if exists audit_projects on public.projects;
create trigger audit_projects after insert or update or delete on public.projects
for each row execute function public.audit_row_change();

drop trigger if exists audit_investors on public.investors;
create trigger audit_investors after insert or update or delete on public.investors
for each row execute function public.audit_row_change();

drop trigger if exists audit_participations on public.participations;
create trigger audit_participations after insert or update or delete on public.participations
for each row execute function public.audit_row_change();

drop trigger if exists audit_settlement_batches on public.settlement_batches;
create trigger audit_settlement_batches after update on public.settlement_batches
for each row execute function public.audit_row_change();

drop trigger if exists audit_weekly_settlements on public.weekly_settlements;
create trigger audit_weekly_settlements after update on public.weekly_settlements
for each row execute function public.audit_row_change();
